const express = require('express');
const router = express.Router();
const db = require('../db');
const PDFDocument = require('pdfkit');

// PDF Export Endpoint
router.get('/export-pdf', async (req, res) => {
    try {
        // Get comprehensive data
        const assets = db.prepare('SELECT * FROM assets').all();
        const actions = db.prepare('SELECT * FROM actions WHERE status = ?').all('pending');

        const critical = assets.filter(a => a.risk_level === 'Critical');
        const high = assets.filter(a => a.risk_level === 'High');
        const healthScore = Math.round(assets.reduce((sum, a) => sum + a.health_score, 0) / assets.length);

        // Create PDF document
        const doc = new PDFDocument({ margin: 50 });

        // Set response headers
        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `attachment; filename=fleet-executive-summary-${new Date().toISOString().split('T')[0]}.pdf`);

        // Pipe PDF to response
        doc.pipe(res);

        // Add content
        // Header
        doc.fontSize(24).fillColor('#662F12').text('Fleet Executive Summary', { align: 'center' });
        doc.fontSize(12).fillColor('#666').text(new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }), { align: 'center' });
        doc.moveDown(2);

        // Fleet Health Score - Large highlight
        doc.fontSize(16).fillColor('#333').text('Fleet Health Score', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(48).fillColor(healthScore > 75 ? '#10B981' : healthScore > 50 ? '#F59E0B' : '#EF4444')
            .text(`${healthScore}%`, { align: 'center' });
        doc.moveDown(1);

        // Key Metrics
        doc.fontSize(16).fillColor('#333').text('Key Performance Indicators', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor('#666');
        doc.text(`• Fleet Uptime: 99.2%`);
        doc.text(`• Active Vehicles: ${assets.length - critical.length}/${assets.length}`);
        doc.text(`• Maintenance Cost (This Week): $12,450`);
        doc.text(`• Critical Assets: ${critical.length}`);
        doc.text(`• High-Risk Assets: ${high.length}`);
        doc.text(`• Pending Actions: ${actions.length}`);
        doc.moveDown(1.5);

        // Risk Breakdown
        doc.fontSize(16).fillColor('#333').text('Risk Level Breakdown', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor('#666');
        doc.text(`Critical: ${critical.length} vehicles (${Math.round(critical.length / assets.length * 100)}%)`);
        doc.text(`High Risk: ${high.length} vehicles (${Math.round(high.length / assets.length * 100)}%)`);
        doc.text(`Watchlist: ${assets.length - critical.length - high.length} vehicles`);
        doc.moveDown(1.5);

        // Top Critical Assets
        if (critical.length > 0) {
            doc.fontSize(16).fillColor('#333').text('Top Critical Assets Requiring Immediate Attention', { underline: true });
            doc.moveDown(0.5);
            doc.fontSize(11).fillColor('#666');
            critical.slice(0, 5).forEach((asset, idx) => {
                doc.text(`${idx + 1}. ${asset.id} (${asset.type}) - ${asset.region}`);
                doc.fontSize(10).fillColor('#999').text(`   Issue: ${asset.predicted_failure} | Health: ${asset.health_score}/100`, { indent: 20 });
                doc.fontSize(11).fillColor('#666');
            });
            doc.moveDown(1.5);
        }

        // Regional Summary
        doc.fontSize(16).fillColor('#333').text('Regional Distribution', { underline: true });
        doc.moveDown(0.5);
        const regions = {};
        assets.forEach(asset => {
            regions[asset.region] = (regions[asset.region] || 0) + 1;
        });
        doc.fontSize(12).fillColor('#666');
        Object.entries(regions).forEach(([region, count]) => {
            const regionCritical = critical.filter(a => a.region === region).length;
            doc.text(`• ${region}: ${count} vehicles (${regionCritical} critical)`);
        });
        doc.moveDown(1.5);

        // Action Items
        doc.fontSize(16).fillColor('#333').text('Recommended Actions', { underline: true });
        doc.moveDown(0.5);
        doc.fontSize(12).fillColor('#666');
        doc.text(`1. Schedule immediate maintenance for ${critical.length} critical vehicles`);
        doc.text(`2. Review and approve ${actions.length} pending maintenance actions`);
        doc.text(`3. Monitor ${high.length} high-risk assets for potential issues`);
        doc.moveDown(2);

        // Footer
        doc.fontSize(10).fillColor('#999').text('Generated by UPS Asset Health Predictor AI', { align: 'center' });
        doc.text('Confidential - For Internal Use Only', { align: 'center' });

        // Finalize PDF
        doc.end();

    } catch (error) {
        console.error('Error generating PDF:', error);
        res.status(500).json({ success: false, error: 'PDF generation failed' });
    }
});

module.exports = router;
